In [2]:
# pip install -U scikit-learn

In [ ]:
# 기본 틀
# 1. from sklearn.linear_model import LinearRegression
# 2. model = LinearRegression()
#    model.fit(x, y)
# 3. prediction = model.predict(x2)

In [3]:
import numpy as np
from sklearn.linear_model import LinearRegression

In [ ]:
# reshape 코드입력

In [4]:
x = np.arange(10).reshape(-1,1)
y = (2*x + 1).reshape(-1,1)

In [5]:
x

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [6]:
y

array([[ 1],
       [ 3],
       [ 5],
       [ 7],
       [ 9],
       [11],
       [13],
       [15],
       [17],
       [19]])

## 모델의 선언, fit(학습), predict(예측)

In [7]:
# 모델 선언
model = LinearRegression()

In [8]:
model

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [9]:
# 학습 mode.fit(데이터, 예측값)
model.fit(x,y) # 위의 결과와 같지만 학습이 완료됨

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [10]:
# 예측 x에 없는 10을 넣어보고 값을 예측해보기
prediction = model.predict([[10.0]])

In [11]:
prediction

array([[21.]])

## 용어정리
- feature : x, 학습을 위한 데이서텟, 예측할 값은 빠져 있다
- label : y, 예측해야할 값, 예측값만 있어야한다

- 학습을 위한 데이터 : Training Set, feature, 모델이 학습하기 위해 필요한 데이터. label이 모두 존재 / x_train, y_train
- 예측을 위한 데이터 : Test Set, feature만 존재 / x_test, y_test

In [13]:
# 1. from sklearn.linear_model import LinearRegression

# 2. model = LinearRegression()
#    model.fit(x_train, y_train)
# 3. prediction = model.predict(x_test) # prediction = y_test로 보면된다

In [ ]:
# 과댜적합, 과소적합하지 않게, Validation Set으로 검증을해야한다
# 단, Validation Set은 학습결과에 영향을 주면 안된다.